# http://travis-ci.org/#!/ipython/ipython
language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
before_install:
    - easy_install -q pyzmq
    - sudo apt-get install pandoc
    - "if [$TRAVIS_PYTHON_VERSION == '3.2'* ]; then pip install -Iv https://pypi.python.org/packages/source/J/Jinja2/Jinja2-2.6.tar.gz"
    - "if [! $TRAVIS_PYTHON_VERSION == '3.2'* ]; then pip install jinja2"
    - pip install -Iv
    - pip install markdown
    - pip install pygments
    - pip install sphinx
install:
    - python setup.py install -q 
script:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.'* ]]; then iptest -w /tmp; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.'* ]]; then iptest3 -w /tmp; fi
