# http://travis-ci.org/#!/ipython/ipython
language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
before_install:
    - easy_install -q pyzmq
    - easy_install pygments
    - easy_install jinja2
    - easy_install markdown
    - sudo apt-get install python-sphinx
    - sudo apt-get install pandoc
install:
    - python setup.py install -q 
script:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.'* ]]; then iptest -w /tmp; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.'* ]]; then iptest3 -w /tmp; fi
